export const mySkills = [
  { title: "Java", icon: "java" },
  { title: "ReactJS", icon: "react" },
  { title: "NextJS", icon: "nextjs" },
  { title: "NodeJS", icon: "nodejs" },
  { title: "ExpressJS", icon: "express" },
  { title: "MongoDB", icon: "mongodb" },
  { title: "JavaScript", icon: "javascript" },
  { title: "TypeScript", icon: "typescript" },
  { title: "Tailwind CSS", icon: "tailwind" },
  { title: "HTML", icon: "html" },
  { title: "CSS", icon: "css" },
  { title: "Redux", icon: "ReduxIcon" },
  { title: "shadcn/ui", icon: "shadcn" },
  { title: "Framer Motion", icon: "FramerMotionIcon" },
  { title: "MySQL", icon: "mysql" },
  { title: "Supabase", icon: "SupabaseIcon" },
  { title: "Firebase", icon: "firebase" },
  { title: "Git", icon: "git" },
  { title: "GitHub", icon: "gitHub" },
  { title: "Docker", icon: "docker" },
  { title: "AWS", icon: "aws" },
  { title: "Vercel", icon: "vercel" },
  { title: "Postman", icon: "postman" },
  { title: "npm", icon: "npm" }
];