export const siteConfig = {
  name: 'varni.is-dev',
  url: 'https://www.vkpatel.in',
  description: 'Portfolio of Patel Varnikumar, Full-Stack Web Developer, Generative AI Engineer & System Design Enthusiast.',
  keywords: [
    'Patel Varnikumar',
    'patel varnikumar',
    'Varnikumar Patel',
    'varni.com',
    'Patel Varnikumar Portfolio',
    'Full Stack Developer',
    'Full-Stack Web Developer',
    'MERN Stack Developer',
    'Generative AI Engineer',
    'Generative AI',
    'LLM Developer',
    'LangChain',
    'RAG',
    'Vector Database',
    'System Design',
    'LLD',
    'HLD',
    'Software Engineer',
    'Web Developer',
    'ML Engineer',
    'Next.js Developer',
    'React Developer',
    'Node.js Developer',
    'MongoDB Developer',
    'Java Developer',
    'Patel Varnikumar Projects',
    'Patel Varnikumar Skills',
    'Patel Varnikumar Experience',
    'Patel Varnikumar Education',
    'Patel Varnikumar Contact',
    'Patel Varnikumar Resume',
  ],
  links: {
    shadcn: 'https://ui.shadcn.com/',
    telegram: 'https://t.me/varni1505',
    twitter: 'https://x.com/varni1512',
    github: 'https://github.com/Varni1512',
    githubProfile: 'https://github.com/Varni1512',
    linkedin: 'https://www.linkedin.com/in/varni1512/',
    resume: 'https://resume.vkpatel.in/', 
    email: 'mailto:varni1505@gmail.com',
    githubUsername: 'Varni1512',
  },
};

export type SiteConfig = typeof siteConfig;

export const META_THEME_COLORS = {
  light: '#ffffff',
  dark: '#09090b',
};